# Generated by Django 3.2.4 on 2021-06-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_prestamomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libromodel',
            old_name='LibroId',
            new_name='libroId',
        ),
        migrations.AlterField(
            model_name='prestamomodel',
            name='prestamoId',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True),
        ),
    ]
