# Generated by Django 3.2.4 on 2021-06-21 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_prestamomodel_prestamofechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamomodel',
            name='prestamoFechaInicio',
            field=models.DateField(db_column='fecha_inicio', default=datetime.date.today, verbose_name='Fecha de inicio del prestamo'),
        ),
    ]
