swagger: '2.0'
info:
  version: '1.0'
  description: 'Api de un Ecommerce de una zapateria'
  title: Zapateria
  contact: 
    email: 'dantello.319@gmail.com'
    name: Daniel Tello
host: '127.0.0.1:8000'
basePath: /
securityDefinitions:
  JWT_token:
    type: "apiKey"
    description: "Bearer token"
    name: "Authorization"
    in: header
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /tipos:
    get:
      summary: /tipos
      tags:
        - Tipo
      operationId: /tipos
      deprecated: false
      produces:
        - application/json
      responses:
        '200':
          description: ''
          headers: {}
    post:
      summary: /tipos
      tags:
        - Tipo
      operationId: Post/tipos
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/~1tiposrequest'
      responses:
        '200':
          description: ''
          headers: {}
  /acciones:
    post:
      summary: /acciones
      tags:
        - Accion
      operationId: /acciones
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/~1accionesrequest'
      responses:
        '200':
          description: ''
          headers: {}
  /registro:
    post:
      summary: /registro
      tags:
        - Usuario
      operationId: /registro
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/~1registrorequest'
      responses:
        '200':
          description: ''
          headers: {}
  /login:
    post:
      summary: /login
      tags:
        - Usuario
      operationId: /login
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/~1loginrequest'
      responses:
        '200':
          description: ''
          headers: {}
  /perfil:
    get:
      summary: /perfil
      tags:
        - Usuario
      operationId: /perfil
      deprecated: false
      produces:
        - application/json
      security:
      -  JWT_token: []
      responses:
        '200':
          description: ''
          headers: {}
  /logout:
    post:
      summary: /logout
      tags:
        - Usuario
      operationId: /logout
      deprecated: false
      produces:
        - application/json
      security:
      -  JWT_token: []
      responses:
        '200':
          description: ''
          headers: {}
  /productos:
    post:
      summary: /productos
      tags:
        - Producto
      operationId: /productos
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/~1productosrequest'
      security:
      -  JWT_token: []
      responses:
        '200':
          description: ''
          headers: {}
  /subirImagen:
    post:
      summary: /subirImagen
      tags:
        - Imagen
      operationId: /subirImagen
      deprecated: false
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: carpeta
          in: query
          required: true
          type: string
          description: ''
        - name: imagen
          in: formData
          required: true
          type: file
          description: 'imagen debe pesar menos de 5MB'
      responses:
        '200':
          description: ''
          headers: {}
  /movimientos:
    post:
      summary: /movimientos
      tags:
        - Movimientos
      operationId: /movimientos
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: Body
          in: body
          required: true
          description: ''
          schema:
            $ref: '#/definitions/~1movimientosrequest'
      security:
      -  JWT_token: []
      responses:
        '200':
          description: ''
          headers: {}
    get:
      summary: /movimientos?pagina=1&porPagina=2
      tags:
        - Movimientos
      operationId: /movimientos?pagina=1&porPagina=2
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: pagina
          in: query
          required: true
          type: integer
          format: int32
          description: ''
        - name: porPagina
          in: query
          required: true
          type: integer
          format: int32
          description: ''
      security:
      -  JWT_token: []
      responses:
        '200':
          description: ''
          headers: {}
definitions:
  /tiposrequest:
    title: /tiposrequest
    example:
      tipoDescripcion: Administrador
    type: object
    properties:
      tipoDescripcion:
        type: string
    required:
      - tipoDescripcion
  /accionesrequest:
    title: /accionesrequest
    example:
      accionDescripcion: EDITAR
    type: object
    properties:
      accionDescripcion:
        type: string
    required:
      - accionDescripcion
  /registrorequest:
    title: /registrorequest
    example:
      email: dantello.3191@gmail.com
      password: '123456'
      nombre: Daniel Tello
      tipo: 1
    type: object
    properties:
      email:
        type: string
      password:
        type: string
      nombre:
        type: string
      tipo:
        type: integer
        format: int32
    required:
      - email
      - password
      - nombre
      - tipo
  /loginrequest:
    title: /loginrequest
    example:
      email: dantello.319@gmail.com
      password: '123456'
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password
  /productosrequest:
    title: /productosrequest
    example:
      productoNombre: zapato de cuero
      productoPrecio: 100
      productoDescripcion: zapato de temporada otoño-invierno
    type: object
    properties:
      productoNombre:
        type: string
      productoPrecio:
        type: number
        format: double
      productoDescripcion:
        type: string
    required:
      - productoNombre
      - productoPrecio
      - productoDescripcion
  /movimientosrequest:
    title: /movimientosrequest
    example:
      movimientoFecha: '2021-07-12 20:38'
      movimientoTipo: EGRESO
      movimientoDetalle:
        - detalleMovimientoCantidad: 2
          detalleMovimientoPrecio: 200
          productoId: 1
        - detalleMovimientoCantidad: 1
          detalleMovimientoPrecio: 150
          productoId: 2
    type: object
    properties:
      movimientoFecha:
        type: string
      movimientoTipo:
        type: string
      movimientoDetalle:
        type: array
        items:
          $ref: '#/definitions/MovimientoDetalle'
    required:
      - movimientoFecha
      - movimientoTipo
      - movimientoDetalle
  MovimientoDetalle:
    title: MovimientoDetalle
    example:
      detalleMovimientoCantidad: 2
      detalleMovimientoPrecio: 200
      productoId: 1
    type: object
    properties:
      detalleMovimientoCantidad:
        type: integer
        format: int32
      detalleMovimientoPrecio:
        type: number
        format: double
      productoId:
        type: integer
        format: int32
    required:
      - detalleMovimientoCantidad
      - detalleMovimientoPrecio
      - productoId
tags:
  - name: Tipo
  - name: Accion
  - name: Usuario
  - name: Producto
  - name: Imagen
  - name: Movimientos
